age = int(input('How old are you? '))
next_age = str(age + 1) 
print('On your next birthday, you will be' + " "+ next_age)
egg = int(input('How many egg cartons do you have?'))
egg_total = str(egg*12) 
print('You have' + " "+ egg_total)
cookies = int(input('How many cookies do you have?'))
people = int(input('How many people are there?'))
per_person = str(cookies/people)
print('Each person may have'+ " "+ per_person + " " 'cookies')