#To show creativity I have added extra sentences at the end of the core requirements
print('Please enter the following: ')
print()
adjective = input('adjective:')
animal = input('animal:')
verb = input('verb:')
exclamation = input('exclamation:')
verb_a = input('verb a:')
verb_b = input('verb b:')
verb_c = input('verb c:')
verb_d = input('verb d:')
print()
print('Your story is:')
print()
print('The other day, I was really in trouble. It all started when I saw a very')
print(adjective + " " + animal+" " + verb+" " + 'down the hallway.'+ " "'"'+exclamation.capitalize()+"!"'"'' I yelled. But all')
print('I could think to do was to'+ " "+verb_a + " "+ 'over and over. Miraculously,')
print('that caused it to stop, but not before it tried to'+ " "+verb_b)
print('right in front of my family.')
print('The'+" " + animal+ " "+ verb_c+ " " 'rapidly into the bush.')
print('And we'+ " "+ verb_d+" " 'happily ever after.')